name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - main
  pull_request_review:
    branches:
      - main
    types: [submitted]

jobs:
  docker-frontend:
    if: github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front  # ✅ Chevalier corrigé
          push: true
          tags: diengsalla/ocr_dev_fullstack_p10:frontend
          

  docker-backend:
    if: github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: actions  # ✅ Ajouté pour cohérence
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        id: buildx  # ✅ ID ajouté
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: diengsalla/ocr_dev_fullstack_p10:backend
          
